# Generated by Django 4.0.4 on 2022-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_home_link_alter_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
