# Generated by Django 4.0.4 on 2022-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
