# Generated by Django 4.0.4 on 2022-05-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='top10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('text', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
