# Generated by Django 4.0.4 on 2022-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='top10',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
