# Generated by Django 4.0.4 on 2022-05-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top10', '0002_top10_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='top10',
            new_name='topt10',
        ),
    ]
